version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: Asia/Bangkok
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: Asia/Bangkok
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: Asia/Bangkok
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
