extends: ['plugin:@typescript-eslint/recommended']
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

rules:
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-empty-function': off
