version: '1'

services:
  backend:
    container_name: 'test-backend'
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    volumes:
      - ./src:/src
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      PORT: ${PORT}
    networks:
      - test-network


  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test-network
networks:
  test-network:
    driver: bridge